### ISSUE TITLE
Virtaul class with no virtual dtor

### ISSUE THREAD

**Issue by Narcolessico** [evpobr/libape#8]
CAntiPredictor has a virtual method but dtor is not virtual. Even if it no base class pointer is deleted, it is a warning/error in some build environments.

**Comment by evpobr** [comment]
Sorry, this is not Monkey's Audio repository :-) Look there: http://www.monkeysaudio.com/.

**Comment by Narcolessico** [comment]
Technically, it's still an issue :-P Ok, thanks!

**Comment by evpobr** [comment]
Technically my project is plain C, so it is not my issue :-)
